name: Deploy Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        EC2_TAG_NAME: testing
        EC2_USER: ubuntu
        SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check EC2 Instance
        id: check
        run: |
          instance_id=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=$EC2_TAG_NAME" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" --output text)

          echo "instance_id=$instance_id"
          
          # Set output properly
          echo "instance_id=${instance_id}" >> $GITHUB_ENV
          
      
